apache/openserverless-task

- setup/opsfile.yml
Added missing $ before OPS in devcluster uninstall.
This fix https://github.com/apache/openserverless/issues/48
> fix(task): small fix in devcluster

- opsroot.json
chore: remving v from opsroot version
> chore: remving v from opsroot version

- setup/nuvolaris/opsfile.yml
Replaced nuv with ops from setup nuvolaris in config and sleep tasks
> fix: Replaced nuv with ops from setup nuvolaris

- runtimes.json
This PR deploys a new `runtimes.json` providing newer Apache OpenServerless java runtimes for version 8,11,17 and 21. V8 it is still set as the default one.
> feat: adding apache openserverless java based runtimes

- opsroot.json
Update to operator build 0.1.0-testing.2409231910 to provide a new user S3_API_URL, when available, after user login to be used to properly implement a `ops web upload` task.
> Implements apache/openserverless#64

- admin/opsfile.yml
- admin/user-crd.yaml
There was an overlap between the AUTH variable (set by ops -login) and the AUTH setup by ops admin adduser. Moved the last to SECRET_AUTH_USER
> chore: auth in useradd doesn't use AUTH

- runtimes.json
This PR adds the experimental go:1.22proxy runtime that can be used to execute action on a remote runtime
> feaure: added the experimental go:1.22proxy runtime

- util/config/configurator.js
- util/config/configurator/configurator.ts
- util/config/configurator/tests/fixtures/valid.json
- util/config/configurator/tests/index.test.ts
This allows digits in a non leading position.
For example, the names HELLO3 and HELLO_A_B_C3 are now allowed.
Closes https://github.com/apache/openserverless/issues/69
> feat: allow digits in the configuration key names

- setup/kubernetes/opsfile.yml
OPERATOR_VOLUME_STORAGE_CLASS require to read the current ops configured kubeconfig. Added a temporary fix. Need a better solution
> chore: operator storage class

- ide/opsfile.yml
added OPS_UPLOAD_FOLDER retrieved from package.json if available. `ops ide serve` will use it instead of `web`. Default will be however `web`.
This wil close https://github.com/apache/openserverless/issues/81.
> feat: ops ide serve

- ide/opsfile.yml
OPSDEV_HOST is now built correctly using protocol//username.apihost
> chore: OPSDEV_HOST in task login

- setup/docker/kind.yaml
Removed wrong containerPort for mongo. See https://github.com/apache/openserverless/issues/85
> chore: wrong containerPort mongo

- ide/deploy/deploy.js
- ide/deploy/package.json
- ide/deploy/watch.js
- prereq.yml
fixed a bug which caused the deploy occurs multiple times on same file. Queued deployment to openwhisk if a deploy for the same action is still in progress.
> fix(deploy): watch

- opsroot.json
updated operator to 0.1.0-incubating.2503142251. This fix json output in ferretdb and postgres
> chore:  updated operator to 0.1.0-incubating.2503142251

- util/upload/assets/index.html
aligned default index.html to same content as the operator. Future version  could eventually deploy better templates.
> chore: aligned default index.html to same content as the operator

- config/opsfile.yml
fixed a typo in OPENWHISK_INVOKER_CONTAINER_POOL_MEMORY inside the slim configuration
> chore: typo in slim config

- opsroot.json
- setup/kubernetes/opsfile.yml
- setup/kubernetes/streamer/k3s-template.yaml
- setup/kubernetes/streamer/nginx-template.yaml
- setup/kubernetes/streamer/opsfile.yml
- setup/kubernetes/streamer/streamer-template.yaml
- setup/opsfile.yml
i've completed the integration of streamer tasks inside the `ops setup mini` command.
In particular, integrated the streamer tasks inside `ops setup kubernetes streamer`
**Notice**
the  OW_APIHOST variable inside `[streamer/opsfile.yml](https://github.com/apache/openserverless-task/pull/112/files#diff-086830ae97d646eba9b8597b4bc9987e381d09a2b8ed58b60541e762dfec63a3) is filled in checking if the controller is deployed in standalone mode (this happens when the `OPERATOR_COMPONENT_INVOKER` is set to false).
Tested the streamer using https://github.com/mastrogpt/streamer-examples sample project
> streamer deploy

- config/opsfile.yml
Added config option MINIO_CONFIG_INGRESS_S3=trye to slim configuration. Resolves https://github.com/apache/openserverless/issues/146
> fix: missing s3 ingress in mini

- config/docopts.md
- config/opsfile.yml
- setup/kubernetes/whisk.yaml
feat: sets load balancer blackbox fraction to 100% by default. This parameter it is already handled by the openserverless-operator as a configurable value, defaulting to 10% if not set into the whisk.yaml.
> Implements apache/openserverless#158

- setup/opsfile.yml
This PR fixes an issue happening when user enter `ops config slim `or `ops config minimal` and then deploys via the o`ps setup devcluster` in such circumstances the APIHOST is not set to miniops.me and the install process hangs up.
> fix: slim and minimal config should use the miniops.me hostname

- config/opsfile.yml
Added a configuration to increase at 10 minutes the openwhisk max time limit. Now is possible to pass a --timeout up to 600000. This resolves https://github.com/apache/openserverless/issues/162
> chore: time limit 10 min

- config/docopts.md
- config/opsfile.yml
- opsroot.json
- setup/kubernetes/crds/whisk-crd.yaml
- setup/kubernetes/opsfile.yml
- setup/kubernetes/whisk.yaml
- util/opsfile.yml
This PR contributes: 
- Config task to setup seaweedfs
- Enable seaweedfs as default S3 API provider in the slim setup, by replacing MINIO.
> [FEATURE] Add support for seaweedfs in config tasks

- opsroot.json
- setup/docker/kind.yaml
- setup/nuvolaris/system-api/api-template.yaml
- setup/nuvolaris/system-api/deploy/buildkit/buildkitd.toml
- setup/nuvolaris/system-api/opsfile.yml
- setup/opsfile.yml
this PR integrates the system-api builder with recent operator support for internal registry.
> Internal registry

- setup/nuvolaris/opsfile.yml
added a param F for eventually specify custom flags in user creation. Useful to create custom users without all services
> chore: support for flags in nuvolaris add-user
