apache/openserverless-task

DISCLAIMER, LICENSE, NOTICE
Adding files: LICENSE, DISCLAIMER, NOTICE. This should fix issue https://github.com/apache/openserverless/issues/54
=> chore: Adding missing files

.gitignore, README.md
Changed NUV_BRANCH to OPS_BRANCH in README.md
Added .idea folder to .gitignore
=> chore: change in README and .gitignore

cloud/aks/cert-manager.yaml, cloud/aks/docopts.txt, cloud/aks/ingress-deploy.yaml, cloud/aks/opsfile.yml, cloud/aws/docopts.txt, cloud/aws/opsfile.yml, cloud/aws/ubuntu.cf, cloud/aws/upsert.json, cloud/eks/cert-manager.yaml, cloud/eks/eks-cluster.yml, cloud/eks/ingress-deploy.yaml, cloud/eks/opsfile.yml, cloud/gcloud/docopts.txt, cloud/gcloud/opsfile.yml, cloud/gke/cert-manager.yaml, cloud/gke/docopts.txt, cloud/gke/ingress-deploy.yaml, cloud/gke/opsfile.yml, cloud/k3s/cert-manager.yaml, cloud/k3s/docopts.txt, cloud/k3s/opsfile.yml, cloud/mk8s/docopts.txt, cloud/mk8s/mk8s.sh, cloud/mk8s/opsfile.yml, cloud/opsfile.yml, cloud/osh/acme-openshift/acme-rbac.yaml, cloud/osh/acme-openshift/acme-setup.yaml, cloud/osh/docopts.txt, cloud/osh/opsfile.yml
This should resolve https://github.com/apache/openserverless/issues/55.
**I need review before merge**
=> migrate the nuv cloud to ops cloud

config/docopts.md, config/docopts.txt
Changed some typos in docopts (both txt and md) in config
=> chore: changed some help typos

opsroot.json
updating to cli build v0.1.0-2409121919.dev
=> chore: updating to cli build v0.1.0-2409121919.dev

prereq.yml
feat: update bun prereq to version 1.1.27
=> feat: update bun prereq to version 1.1.27

setup/nuvolaris/opsfile.yml
As requested in the openserverless/issues/63
=> ops -login to auth nuvolaris user(task):

util/config/README.md, util/config/configurator/package.json
This PR adds some documentation to clarify how to run, test and build the configurator, related to https://github.com/apache/openserverless/issues/65
=> Add a readme on the wizard

admin/opsfile.yml
Renamed two $NUV_TMP variables to $OPS_TMP
=> chore(renamed NUV_TMP to OPS_TMP:

cloud/k3s/docopts.txt, cloud/k3s/opsfile.yml, cloud/mk8s/docopts.txt, cloud/mk8s/opsfile.yml, config/opsfile.yml, setup/docker/opsfile.yml, setup/docopts.md, setup/docopts.txt
Hello,
this PR contains commits to fix `ops cloud k3s / mk8s` and `ops config use`
Note: In ops cloud, i changed `USERNAME` to `INSTALL_USER`  to avoid any possible clash with USERNAME env variable coming from some shells
=> fixing tasks for testing

docopts.md
removed ops web from dev utilities. Now it's under ops util
=> chore: updated root docopts.md

setup/kubernetes/opsfile.yml
=> chore: operator storage class

opsfile.yml, opsroot.json, setup/kubernetes/opsfile.yml, setup/nuvolaris/opsfile.yml, setup/nuvolaris/postgres.js, update/opsfile.yml
Hello,
these modifications are required to fix things and let the testing work
=> testing-linux

cloud/mk8s/opsfile.yml
removed realpath from cloud/mk8s
=> chore: removed realpath

cloud/aks/docopts.txt, cloud/aks/opsfile.yml, cloud/azcloud/docopts.txt, cloud/azcloud/opsfile.yml, config/opsfile.yml
Added zone manipulation (DNS) commands to azcloud.
Changed aks to support a resource group name different than the name of the cluster
=> chore: changes azcloud and aks

runtimes.json
chore: updated go proxy client
=> chore: updated go proxy client

setup/nuvolaris/minio.js, setup/nuvolaris/opsfile.yml
As we changed in configuration variables from minio to s3, it's required to change also the minio hello action.
All test passed
=> chore: changed minio_ to s3_ in hello

runtimes.json
using go proxy client v1.22proxy-2410150849 with code HASH and logging inclusion
=> using go proxy client v1.22proxy-2410150849

opsroot.json, setup/kubernetes/opsfile.yml, setup/nuvolaris/opsfile.yml, setup/opsfile.yml, update/opsfile.yml
Hello these modifications have been made after testing discovered some things not working properly.
=> additional modification for testing

cloud/aks/opsfile.yml, cloud/azcloud/opsfile.yml, cloud/eks/eks-cluster.yml, cloud/eks/opsfile.yml, config/docopts.md, config/docopts.txt, config/opsfile.yml
Multiple fixes:
- added --project for config aks and eks in config docopts
- aligned variables between config and eks cluster creation
- improved kubeconfig extraction in aks
- azcloud dns is now able to handle child zone creation
=> chore: testing

util/config/configurator.js, util/config/configurator/configurator.ts, util/config/configurator/tests/fixtures/valid.json, util/config/configurator/tests/fixtures/with-defaults.json
This PR enhances the configurator with default values.
close https://github.com/apache/openserverless/issues/61
=> Add default values for configurator

cloud/azcloud/opsfile.yml, config/opsfile.yml, opsroot.json
These changes bring improvements to the azcloud cloud command.
Note: Changed the operator to "incubating"
=> Changes to azcloud

opsroot.json, prereq.yml
Upgraded kind version from 0.17.0 to 0.22.0.
Upgraded operator image from 2410261127 to 2411132042
=> chore: upgraded kind and operator

runtimes.json
=>  update to python runtimes

ide/deploy/info.js, ide/opsfile.yml
Added a script that can be used to extract values from package.json and use them in taskfile scripts. Implemented the ability to configure the directory from which to retrieve web assets as per https://github.com/apache/openserverless/issues/81
=> feat: add script info to deploy

admin/docopts.md, admin/opsfile.yml, admin/user-crd.yaml, config/docopts.md, config/opsfile.yml, opsroot.json, setup/docker/kind.yaml, setup/kubernetes/crds/whisk-crd.yaml, setup/kubernetes/crds/whisk-user-crd.yaml, setup/kubernetes/roles/operator-roles.yaml, setup/kubernetes/whisk.yaml, util/opsfile.yml
This PR contributes the change to configure operator apache/openserverless-operator:0.1.0-incubating.2412081158 with ETCD and MILVUS support
=> feature: MILVUS and ETCD support

config/docopts.md, config/opsfile.yml
cannot use mongodb flasg to set MongoDB database size
=> fix: cannot use mongodb flasg to set MongoDB database size

opsroot.json
=>  chore: new operator

opsroot.json, util/opsfile.yml
new operator version - 2501041404
=> new operator and fix operator's version check

setup/kubernetes/opsfile.yml
=> chore: fix milvus role count

opsroot.json, prereq.yml, runtimes.json
Hashed password saved in couchdb
=> hashed password

cloud/aks/opsfile.yml, runtimes.json
Runtimes updated to 2501172243
=> Runtimes update

opsroot.json
updated runtimes to tag 2501191626
=> chore: runtimes update

ide/deploy/index.js, ide/opsfile.yml
As in the subject. There were a mistake in how process group is retrieved.
This need further testing on windows
=> fix terminate in ops ide devel

ide/opsfile.yml
Improved process termination in `ops ide devel` task
=> improved termination for devel

opsroot.json
updated operator to 0.1.0-incubating.2502111346
=> chore: new operator version

devel/docopts.md, devel/ferretdb/docopts.md, devel/ferretdb/ferretdb.js, devel/ferretdb/opsfile.yml, devel/minio/docopts.md, devel/minio/minio.js, devel/minio/opsfile.yml, devel/opsfile.yml, devel/psql/docopts.md, devel/psql/opsfile.yml, devel/psql/psql.js, devel/redis/docopts.md, devel/redis/opsfile.yml, devel/redis/redis.js, ide/docopts.md, setup/docopts.md
feat: ops devel
ported ops devel from nuv to ops.
This for the issue https://github.com/apache/openserverless/issues/103
=> feat: ops devel

setup/nuvolaris/opsfile.yml, setup/opsfile.yml
replaced grep with ripgrep in setup and setup/nuvolaris. 
These changes are for the issue https://github.com/apache/openserverless/issues/101
=> fix: replace grep with ripgrep

devel/ferretdb/ferretdb.js, devel/minio/docopts.md, devel/minio/minio.js, devel/psql/docopts.md, devel/psql/opsfile.yml, devel/psql/psql.js, devel/redis/opsfile.yml, devel/redis/redis.js, prereq.yml
Reviewed all the tasks, docopts and bun scripts.
`ops devel psql sql` now accepts query on stdin or from a sql file.
=> Improved ops devel

devel/psql/psql.js
fixed a bug in argv parsing for ops psql task bun script
=> chore: argv parsing in psql

ide/deploy/index.js, ide/docopts.md, ide/opsfile.yml
Implemented what requested in issue https://github.com/apache/openserverless/issues/99
=> feat: ops ide devel --fast

config/docopts.md, config/opsfile.yml, setup/kubernetes/crds/whisk-crd.yaml, setup/kubernetes/whisk.yaml
Implemented what requested in issue https://github.com/apache/openserverless/issues/105.
Furthermore, added a parameter to increase etcd quota backend bytes
=> feat: etcd quota and auto-compaction

ide/deploy/index.js
=> chore: fix ide devel

ide/opsfile.yml, util/docopts.md, util/opsfile.yml, util/upload.js, util/upload/assets/index.html, util/upload/src/lib/utils.ts, util/upload/src/upload.ts
This PR add some useful tasks for cleanup for web bucket.
=> ops ide undeploy and ops util clean

cloud/azcloud/opsfile.yml, util/opsfile.yml
I fixed:
- azcloud command
- removed grep with ripgrep in util
=> minor fixes

runtimes.json
updated runtimes to 2501172243. Added python 3.13
=> chore: runtimes 2501172243

config/opsfile.yml, setup/nuvolaris/opsfile.yml, setup/opsfile.yml
this pr should manage autoconfiguration of openserverless allowing to autonable slim if no other configurations were provided
=> autoconfig for devcluster

ide/deploy/client.js, ide/deploy/deploy.js, ide/deploy/index.js, ide/deploy/serve.js
the deploy child process needs to be explicitly killed if main pid is killed
=> fix: kill child if terminated

ide/deploy/client.js, ide/deploy/index.js, ide/deploy/watch.js, ide/opsfile.yml
removed kill -9 because SIGKILL is not handled by bun and the watchers are not removed
=> fix: task kill

setup/docker/opsfile.yml, setup/docker/space.py, setup/opsfile.yml
resolves https://github.com/apache/openserverless/issues/150
Added `ops setup docker check-space` to be used in `ops setup mini`
=> feat:  check disk space before setup

prereq.yml, setup/docker/opsfile.yml, setup/opsfile.yml
also updated deps including zip, uv e kubefwd
=> check containerd

devel/psql/psql.js, opsroot.json, setup/docker/space.py, setup/docopts.md, setup/opsfile.yml
this is required after the changes in operator. See https://github.com/apache/openserverless/issues/151.
Update operator to 0.1.0-incubating.2507122132
=> fix: default schema in ops devel psql

ide/opsfile.yml
this helps avoiding errors in deployments
=> Auth check

cloud/aws/opsfile.yml, cloud/eks/opsfile.yml, debug/runtime/opsfile.yml, ide/nodejs/opsfile.yml, setup/kubernetes/opsfile.yml
there is now an ops setup kubernetes configure allowing to create a configuration in kubernetes without actually launching the operator - very useful for development
=> Support for ops setup kubernetes configure

ide/deploy/serve.js, ide/devcontainer.json, ide/docopts.md, ide/opsfile.yml
=> fixed the serve issue and added the devcontainer check and command
